apiVersion: apps/v1
# apiVersion: extensions/v1beta1 # 舊版使用
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx
    # name: nginx # 舊版使用
    # env: dev # 舊版使用
    # color: green # 舊版使用
spec:
  # replicas: 3 # number of pods need to create
  selector:
    matchLabels:
      app: nginx
      # name: nginx # 舊版使用
      # env: dev # 舊版使用
      # color: green # 舊版使用
  template:
    metadata:
      labels:
        app: nginx
        # name: nginx # 舊版使用
        # env: dev # 舊版使用
        # color: green # 舊版使用
    spec:
      hostNetwork: false # 
      containers:
      - name: nginx
        image: nginx:1.7.9
        imagePullPolicy: Always # 當有新的映像檔更新時會自動去拉映像檔的功能
        ports:
        - containerPort: 80
        env:
        - name: JIM_SPECIFIC_VERSION
          value: jim_deployment_v1
        - name: JIM_SECRET_SPECIFIC_USERNAME
          valueFrom:
            secretKeyRef:
              name: jimkey
              key: username
        - name: JIM_SECRET_SPECIFIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jimkey
              key: password