apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  labels:
    app: nginx
spec:
  # externalTrafficPolicy: Cluster # comment out this to use ingress instead of service
  # type: LoadBalancer # use extenal IP
  type: NodePort # use NAT inside k8s
  selector:
    app: nginx
    # name: nginx
    # env: dev
    # color: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # front-end: Note: A Service can map any incoming port to a targetPort. By default and for convenience, the targetPort is set to the same value as the port field

