---
- name: pull nginx:1.13.7 image
  shell: |
    docker pull nginx:1.13.7
  # become: yes
 
- name: Copy custom index.html file 
  copy:
    src: index.html
    dest: /tmp/index.html
    mode: 0644

- name: Run nginx container
  shell: |
    docker run -v /tmp:/usr/share/nginx/html -p 80:80 -d nginx:1.13.7
  # become: yes

